name: imersao-go-driver

services:
  imersao-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data-db:/var/lib/postgresql/data

  imersao-rabbitmq:
    image: rabbitmq:3
    restart: always
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_HTTP_PORT}:15672"
    volumes:
      - data-rabbitmq:/var/lib/rabbitmq

networks:
  default:
    driver: bridge

volumes:
  data-db:
  data-rabbitmq:
