CREATE TABLE users (
    id SERIAL,
    name VARCHAR(80) NOT NULL,
    login VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    deleted BOOL DEFAULT FALSE,
    PRIMARY KEY (id)
);